print("hello Homie")
print("ฉันชื่อมุก")
Print ("ยินดีที่รู้จัก ฉับ Chopper")
print ("หิวไหม")
Print ("ไม่")
Print ("งั้นดื่มล่ะ?")
Print ("เลี้ยงสิ")
Print ("ได้")
Print ("ชานมไข่มุกนะ")
Print ("OK")
